apiVersion: kudo.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: flink-1.7
  namespace: default
spec:
  framework:
    name: flink # this needs to link to an existing framework defined in the *-framework.yaml
    kind: Framework
  # Add fields here
  version: "1.7" # this will be the version label
  parameters:
    - name: FLINK_TASKMANAGER_REPLICAS
      description: Number of task managers to run
      default: "2"
    - name: FLINK_JOBMANAGER_REPLICAS
      description: Number of job managers to run
      default: "1"
    - name: ZOOKEEPER_URL
      description: Connection information for Zookeeper
      default: "zk:2181"
    - name: ZOOKEEPER_PATH
      description: path to store Flink data in Zookeeper
      defaut: "/flink"
    - name: HIGH_AVAILABILITY
      description: Defines high-availability mode used for the cluster execution. To enable high-availability, set this mode to "ZOOKEEPER" or specify FQN of factory class.
      default: NONE
  templates:
    storage.yaml: |
    # snapshots
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: snapshots
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      ---
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ha
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    # HA PVs
    configmap.yaml: |
      apiVersion: v1
      data:
        flink.conf: |
          #==============================================================================
          # High Availability
          #==============================================================================

          # The high-availability mode. Possible options are 'NONE' or 'zookeeper'.
          #
          high-availability: zookeeper

          # The path where metadata for master recovery is persisted. While ZooKeeper stores
          # the small ground truth for checkpoint and leader election, this location stores
          # the larger objects, like persisted dataflow graphs.
          # 
          # Must be a durable file system that is accessible from all nodes
          # (like HDFS, S3, Ceph, nfs, ...) 
          #
          high-availability.storageDir: file:///ha/

          state.savepoints.dir: file:///snapshots/
          state.checkpoints.dir: file:///snapshots/

          # The list of ZooKeeper quorum peers that coordinate the high-availability
          # setup. This must be a list of the form:
          # "host1:clientPort,host2:clientPort,..." (default clientPort: 2181)
          #
          high-availability.zookeeper.quorum: {{ZOOKEEPER_URL}}
          high-availability.zookeeper.path.root: {{ZOOKEEPER_PATH}}
      kind: ConfigMap
      metadata:
        name: config
    services.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: jobmanager
        namespace: {{NAMESPACE}}
      spec:
        ports:
        - name: rpc
          port: 6123
        - name: blob
          port: 6124
        - name: query
          port: 6125
        - name: ui
          port: 8081
        selector:
          app: {{NAME}}
          component: {{NAME}}-jobmanager
    taskmanager-deployment.yaml: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: taskmanager
      spec:
        replicas: {{FLINK_TASKMANAGER_REPLICAS}}
        template:
          metadata:
            labels:
              app: flink
              component: {{NAME}}-taskmanager
          spec:
            containers:
            - name: taskmanager
              image: flink:1.7
              args:
              - taskmanager
              ports:
              - containerPort: 6121
                name: data
              - containerPort: 6122
                name: rpc
              - containerPort: 6125
                name: query
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{NAME}}-jobmanager
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{name}}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{name}}-snapshot
    jobmanager-deployment.yaml: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: jobmanager
      spec:
        replicas: {{FLINK_JOBMANAGER_REPLICAS}}
        template:
          metadata:
            labels:
              app: {{NAME}}
              component: {{NAME}}-jobmanager
          spec:
            containers:
            - name: jobmanager
              image: flink:1.7
              args:
              - jobmanager
              ports:
              - containerPort: 6123
                name: rpc
              - containerPort: 6124
                name: blob
              - containerPort: 6125
                name: query
              - containerPort: 8081
                name: ui
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{NAME}}-jobmanager
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{name}}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{name}}-snapshot
  tasks:
    jobmanager:
      resources:
        - jobmanager-deployment.yaml
    jobmanager-service:
      resources:
        - services.yaml
    taskmanager:
      resources:
        - taskmanager-deployment.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: flink
          strategy: serial
          steps:
            - name: jobmanager
              tasks:
                - jobmanager
                - jobmanager-service
                - taskmanager