apiVersion: kudo.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: flink-1.7
  namespace: default
spec:
  framework:
    name: flink # this needs to link to an existing framework defined in the *-framework.yaml
    kind: Framework
  # Add fields here
  version: "1.7" # this will be the version label
  parameters:
    - name: FLINK_TASKMANAGER_REPLICAS
      description: Number of task managers to run
      default: "2"
    - name: FLINK_JOBMANAGER_REPLICAS
      description: Number of job managers to run
      default: "1"
    - name: ZOOKEEPER_URL
      description: Connection information for Zookeeper
      default: "zk-zk-0.zk-hs:2181,zk-zk-1.zk-hs:2181,zk-zk-2.zk-hs:2181"
    - name: ZOOKEEPER_PATH
      description: path to store Flink data in Zookeeper
      defaut: "/flink"
    - name: HIGH_AVAILABILITY
      description: Defines high-availability mode used for the cluster execution. To enable high-availability, set this mode to "ZOOKEEPER" or specify FQN of factory class.
      default: NONE
  templates:
    storage.yaml: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: snapshots
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
      ---
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ha
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
    services.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: jobmanager
        namespace: {{NAMESPACE}}
      spec:
        ports:
        - name: rpc
          port: 6123
        - name: blob
          port: 6124
        - name: query
          port: 6125
        - name: ui
          port: 8081
        selector:
          app: {{NAME}}
          component: {{NAME}}-jobmanager
    taskmanager-deployment.yaml: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: taskmanager
      spec:
        replicas: {{FLINK_TASKMANAGER_REPLICAS}}
        template:
          metadata:
            labels:
              app: flink
              component: {{NAME}}-taskmanager
          spec:
            containers:
            - name: taskmanager
              image: kudobuilder/flink:1.7.2
              args:
              - taskmanager
              - "-Dhigh-availability={{HIGH_AVAILABILITY}}"
              - "-Dhigh-availability.storageDir=file:///ha/"
              - "-Dstate.savepoints.dir=file:///snapshots/"
              - "-Dstate.checkpoints.dir=file:///snapshots/"
              - "-Dhigh-availability.zookeeper.quorum={{ZOOKEEPER_URL}}"
              - "-Dhigh-availability.zookeeper.path.root={{ZOOKEEPER_PATH}}"
              ports:
              - containerPort: 6121
                name: data
              - containerPort: 6122
                name: rpc
              - containerPort: 6125
                name: query
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{NAME}}-jobmanager
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{NAME}}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{NAME}}-snapshots
    jobmanager-deployment.yaml: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: jobmanager
      spec:
        replicas: {{FLINK_JOBMANAGER_REPLICAS}}
        template:
          metadata:
            labels:
              app: {{NAME}}
              component: {{NAME}}-jobmanager
          spec:
            containers:
            - name: jobmanager
              image: kudobuilder/flink:1.7.2
              args:
              - jobmanager
              - "-Dhigh-availability={{HIGH_AVAILABILITY}}"
              - "-Dhigh-availability.storageDir=file:///ha/"
              - "-Dstate.savepoints.dir=file:///snapshots/"
              - "-Dstate.checkpoints.dir=file:///snapshots/"
              - "-Dhigh-availability.zookeeper.quorum={{ZOOKEEPER_URL}}"
              - "-Dhigh-availability.zookeeper.path.root={{ZOOKEEPER_PATH}}"
              ports:
              - containerPort: 6123
                name: rpc
              - containerPort: 6124
                name: blob
              - containerPort: 6125
                name: query
              - containerPort: 8081
                name: ui
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{NAME}}-jobmanager
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{NAME}}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{NAME}}-snapshots
  tasks:
    common:
      resources:
        - storage.yaml
    jobmanager:
      resources:
        - jobmanager-deployment.yaml
    jobmanager-service:
      resources:
        - services.yaml
    taskmanager:
      resources:
        - taskmanager-deployment.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: flink
          strategy: serial
          steps:
            - name: jobmanager
              tasks:
                - common
                - jobmanager
                - jobmanager-service
                - taskmanager