apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: redis
  name: rediscluster1
spec:
  frameworkVersion:
    name: redis-5.0.1
    namespace: default
    type: FrameworkVersion
  # Add fields here
  parameters:
    INSTANCES: "6"
