apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: mysql
  name: mysql
spec:
  frameworkVersion:
    name: mysql-57
    namespace: default
    type: FrameworkVersions
  # Add fields here
  parameters:
    PASSWORD: password
    BACKUP_FILE: backup.sql
